version: '3.9'

services:
  app:
    container_name: trello-clone-fe
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh